# Generated by Django 3.1.5 on 2021-02-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='we',
            name='all_temp',
        ),
    ]
